### ISSUE TITLE
Add a test case to check the value of public key modulus

### ISSUE THREAD

**Issue by mpnd** [NICTA/javallier#14]
In `Assumptions` test class, add a test case to check whether the assumption that the modulus of a public key is always odd and is greater than 4.

**Comment by wilko77** [comment]
I don't see how you would test that in the `Assumptions` test class, because you would have to create public keys and these are either created to fulfil or violate the assumptions. So what's the point of a test if you know the answer beforehand.

If this assumption is important, then it probably would be better to test for it in the constructor of `PaillierPublicKey`.

**Comment by mpnd** [comment]
I agree with @wilko77. Also, `Assumptions` test class has been removed in 84b894a2a7eb447ffd6da967fa507b47ca9319b5 because the assumptions tested here are only valid for base 2 encoding.
